# Generated by Django 3.2.4 on 2022-06-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_category_nominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='year',
            field=models.CharField(default='2022', max_length=100),
            preserve_default=False,
        ),
    ]
