# Generated by Django 3.2.4 on 2022-06-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_nominee_nominated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominated_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nominated', models.IntegerField(default=0)),
            ],
        ),
    ]
