# Generated by Django 3.2.4 on 2022-06-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_nominated_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='nominated',
        ),
        migrations.AlterField(
            model_name='nominated_brand',
            name='nominated',
            field=models.IntegerField(default=1),
        ),
    ]
