# Generated by Django 3.2.4 on 2022-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220610_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominated_brand',
            name='category',
            field=models.CharField(default='dd', max_length=500),
            preserve_default=False,
        ),
    ]
