# Generated by Django 3.2.4 on 2022-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_nomination_visiblility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_visiblility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
    ]
