# Generated by Django 3.2.4 on 2022-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_vote_visiblility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('category', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=100)),
                ('vote_count', models.IntegerField(default=0)),
                ('secret_code', models.CharField(max_length=100)),
            ],
        ),
    ]
