# Generated by Django 5.2.4 on 2025-10-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_candidate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='best_selling_product',
            field=models.BooleanField(default=False),
        ),
    ]
