# Generated by Django 5.2.4 on 2025-10-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_event_paymentwebhookevent_vote_votepurchase_voter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=240),
        ),
    ]
