# Generated by Django 5.2.4 on 2025-10-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_candidate_slug_alter_category_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
