# Generated by Django 5.2.4 on 2025-10-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_candidate_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home Slider',
                'verbose_name_plural': 'Home Sliders',
                'ordering': ['order'],
            },
        ),
    ]
