# Generated by Django 5.2.4 on 2025-10-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_homeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_url', models.URLField(blank=True, help_text='Leave blank to hide the Vote button.')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Config',
            },
        ),
    ]
